apiVersion: web.valon.dev/v1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: website-operator
    app.kubernetes.io/managed-by: kustomize
  name: website-sample
spec:
  # TODO(user): Add fields here
